### PR TITLE
Immediately return mime-type if extension is unknown

### PR DESCRIPTION
**Pull request by gisostallenberg**
See #3

### CODE REVIEW

**Comment by dfridrich** [comment]
There is a conflict with min PHP version in Travis. Can you change min. PHP in composer.json to solve this issue? Version 2 can have min. PHP version 5.5.9, what do you think? Or we can use older symfony/http-foundation?

**Comment by gisostallenberg** [comment]
The requirement of symfony/http-foundation can be '^2.8 || ^3.0', composer.lock [should be added](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file) and the travis config updated adding the following:

``` yml
before_install:
  - if [[ $TRAVIS_PHP_VERSION = 5.4 ]]; then composer update; fi;
```

**Comment by gisostallenberg** [comment]
I will add this to the PR

**Comment by gisostallenberg** [comment]
I fixed the travis run, but you [use code](https://github.com/dfridrich/PhpMimeType/blob/5e5d40809e996c1649222d82b2c456cb5fbdcd79/src/MimeType.php#L138) only [available](http://php.net/manual/en/splfileobject.fread.php) in PHP >= 5.5.11

**Comment by dfridrich** [comment]
You are right, SPL is from 5.5.11, so let's have 5.5.11 as the min PHP version in version 2 of this package.

**Comment by gisostallenberg** [comment]
Will you change this and update the composer.lock?

**Comment by dfridrich** [comment]
Yes :)

**Pull request merged**
